### ISSUE TITLE
[Bug] Data parallel lgbm throws exception when splitting a leaf

### ISSUE THREAD

**Issue by vollis** [lightgbm-org/LightGBM#5222]
## Description
The variable cnt could be 0 in code below commented with // BUG:
```
// data_partition.hpp
void Split(int leaf, const Dataset* dataset, int feature,
             const uint32_t* threshold, int num_threshold, bool default_left,
             int right_leaf) {
    Common::FunctionTimer fun_timer("DataPartition::Split", global_timer);
    // get leaf boundary
    const data_size_t begin = leaf_begin_[leaf];
   // BUG: this cnt could be 0
    **_const data_size_t cnt = leaf_count_[leaf];_**
    auto left_start = indices_.data() + begin;
   // BUG: if cnt =0, the nblock -> 0
  // 
    const auto left_cnt = runner_.Run<false>(
        cnt,
        [=](int, data_size_t cur_start, data_size_t cur_cnt, data_size_t* left,
            data_size_t* right) {
          return dataset->Split(feature, threshold, num_threshold, default_left,
                                left_start + cur_start, cur_cnt, left, right);
        },
        left_start);
```
then causing the last line in code below (nblock-1=-1) to throw an index out of range error
```
// threading.h
 template<bool FORCE_SIZE>
  INDEX_T Run(
      INDEX_T cnt,
      const std::function<INDEX_T(int, INDEX_T, INDEX_T, INDEX_T*, INDEX_T*)>& func,
      INDEX_T* out) {
    int nblock = 1;
    INDEX_T inner_size = cnt;
    if (FORCE_SIZE) {
      Threading::BlockInfoForceSize<INDEX_T>(num_threads_, cnt, min_block_size_,
                                             &nblock, &inner_size);
    } else {
      Threading::BlockInfo<INDEX_T>(num_threads_, cnt, min_block_size_, &nblock,
                                    &inner_size);
    }
    ...

    data_size_t left_cnt = left_write_pos_[nblock - 1] + left_cnts_[nblock - 1];
```
## Environment info

LightGBM version or commit hash: any version before 2022/5/18

Command(s) you used to install LightGBM
```shell
I used the windows debug version to train a model from 2 machines, with  is_pre_partition = true tree_learner = data 

```

**Comment by vollis** [comment]
Is it because that sometimes the local leaf holds no data samples, and in such case we can just skip the threading::Run?

**Comment by shiyu1994** [comment]
@vollis Thanks for using LightGBM and find out the bug. A related fix about local leaves containing no data sample is
https://github.com/microsoft/LightGBM/pull/4185,
and the fix has been merged since v3.3.0.
Which version of LightGBM are you using?

**Comment by vollis** [comment]
Your fix is 1 year ago, but I pulled the master on 5/18/2022, and the bug is still there. 

> @vollis Thanks for using LightGBM and find out the bug. A related fix about local leaves containing no data sample is #4185, and the fix has been merged since v3.3.0. Which version of LightGBM are you using?

**Comment by jameslamb** [comment]
Thanks for reporting this! Similar to my comments in https://github.com/microsoft/LightGBM/issues/5221#issuecomment-1134089385...it's really difficult for us to investigate this without more information. LightGBM is a large and complex software project, so it can take large amount of effort to evaluate claims like "this particular line of this file could fail because this variable could have a particular value" that aren't accompanied by any other information or evidence.

More information about how you're using LightGBM and the conditions under which you see undesirable behavior will help maintainers to narrow down how an issue could happen, and develop a corresponding fix and test.

Are you able to provide a reproducible example demonstrating this behavior? Or at least the full list of parameters you used?

I'm also curious about the statement "I used the windows debug version"...does the same issue you experienced also happen if you use a non-debug build of LightGBM?

**Comment by vollis** [comment]
> Thanks for reporting this! Similar to my comments in [#5221 (comment)](https://github.com/microsoft/LightGBM/issues/5221#issuecomment-1134089385) really difficult for us to investigate this without more information. LightGBM is a large and complex software project, so it can take large amount of effort to evaluate claims like "this particular line of this file could fail because this variable could have a particular value" that aren't accompanied by any other information or evidence.
> 
> More information about how you're using LightGBM and the conditions under which you see undesirable behavior will help maintainers to narrow down how an issue could happen, and develop a corresponding fix and test.
> 
> Are you able to provide a reproducible example demonstrating this behavior? Or at least the full list of parameters you used?
> 
> I'm also curious about the statement "I used the windows debug version"...does the same issue you experienced also happen if you use a non-debug build of LightGBM?

The bug only occurs when running lgbm on one of my dataset, and I think it will only be triggered by some special data distribution. And I can't share the dataset as it's not a public dataset. 
The parameters I used are is_pre_partition = true tree_learner = data, objective=lambdarank, metric=ndcg, label_column=0, is_pre_partition = true, query_id = 0, is_enable_sparse = true.

I fixed the bug as I described in the previous comment, maybe it's just an adhoc workaround but at least it's working for me and my dataset. 
I am posting it here because I think that some of the contributors is more familiar with the logic of the code and might know the root cause right away without reproducing it first.
